import { readFileSync, writeFileSync } from 'node:fs';

/**
 * Build src/data/world.ts — the world's coastline, in İstanbul's coordinates.
 *
 * WHY THE SAME COORDINATES
 * The map already has one projection: Web Mercator, normalised so the
 * İstanbul window is 100 units wide. Applying that same formula to any point
 * on Earth gives a position in the same space — a very large number, but the
 * same space. So the world is not a second map that has to be swapped in, it
 * is the same map seen from further away, and zooming between them is one
 * continuous movement rather than a mode change.
 *
 * One degree of longitude is about 108.7 units here, so the whole world is
 * roughly 39,000 units across: a zoom range of about 1:5400 from the network
 * to the planet, which SVG handles without complaint because every path is
 * re-rasterised at the size it is drawn.
 *
 * Natural Earth 110m, simplified hard. At world zoom a fjord is a subpixel.
 *
 *   curl -sL https://raw.githubusercontent.com/nvkelso/natural-earth-vector/\
 *     master/geojson/ne_110m_land.geojson -o world.geojson
 *   node scripts/build-world.mjs world.geojson
 */
const SRC = process.argv[2] ?? 'world.geojson';
const EPS = Number(process.argv[3] ?? 0.55); // degrees
const W_LON = 28.6,
  E_LON = 29.52,
  N_LAT = 41.31;

const merc = (lat) => Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 180 / 2));
const XS = 100 / (E_LON - W_LON);
const YS = XS * (180 / Math.PI);
const Y1 = merc(N_LAT);
// Mercator runs to infinity at the poles; clamp where every atlas clamps.
const LAT_MAX = 83;
const px = (lat, lon) => [
  (lon - W_LON) * XS,
  (Y1 - merc(Math.max(-LAT_MAX, Math.min(LAT_MAX, lat)))) * YS,
];

function rdp(pts, eps) {
  if (pts.length < 3) return pts;
  let maxD = 0,
    idx = 0;
  const a = pts[0],
    b = pts[pts.length - 1];
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perp(pts[i], a, b);
    if (d > maxD) {
      maxD = d;
      idx = i;
    }
  }
  if (maxD <= eps) return [a, b];
  return rdp(pts.slice(0, idx + 1), eps)
    .slice(0, -1)
    .concat(rdp(pts.slice(idx), eps));
}
function perp(p, a, b) {
  const dx = b[0] - a[0],
    dy = b[1] - a[1];
  const den = dx * dx + dy * dy;
  if (den === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / den));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

const geo = JSON.parse(readFileSync(SRC, 'utf8'));
const rings = [];
for (const f of geo.features) {
  const polys =
    f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    // Outer ring only. Holes at this scale are lakes, and the map has no lakes.
    const ring = rdp(poly[0], EPS);
    if (ring.length < 4) continue;
    rings.push(ring);
  }
}

const f2 = (n) => Number(n.toFixed(1));
/**
 * Three copies, at −360°, 0° and +360°.
 *
 * İstanbul sits at 29°E, so a single copy leaves the Pacific torn down the
 * middle of the frame when the world is centred on it. Repeating the land
 * either side is what every slippy map does and it costs three times almost
 * nothing.
 */
const paths = [];
for (const shift of [-360, 0, 360]) {
  for (const ring of rings) {
    let d = '';
    let last = null;
    for (const [lon, lat] of ring) {
      const [x, y] = px(lat, lon + shift).map(f2);
      if (last && last[0] === x && last[1] === y) continue;
      d += (d === '' ? 'M' : 'L') + x + ',' + y;
      last = [x, y];
    }
    if (d.length > 12) paths.push(d + 'Z');
  }
}

const ts = `/**
 * THE WORLD, in this map's own coordinates.
 *
 * Natural Earth 110m land, projected with exactly the İstanbul window's Web
 * Mercator and simplified to about ${Math.round(EPS * 111)} km — at the zoom this is drawn at, a
 * fjord is a subpixel and a coastline is a silhouette.
 *
 * It shares the network's coordinate space on purpose. Zooming out from the
 * Bosphorus to the planet is then one continuous movement rather than a swap
 * between two maps, and a reader who has never heard of Marmaray can see where
 * on Earth it is by pulling back.
 *
 * GENERATED by scripts/build-world.mjs. Natural Earth is public domain.
 */

/** Land silhouettes, repeated at -360, 0 and +360 degrees of longitude. */
export const WORLD: string[] = ${JSON.stringify(paths)};

/** Where the network sits, for the marker drawn at world zoom. */
export const ISTANBUL = { x: ${f2(px(41.02, 29.05)[0])}, y: ${f2(px(41.02, 29.05)[1])} };

/** The whole planet, in these units: 360 degrees of longitude. */
export const WORLD_W = ${f2(360 * XS)};
`;
writeFileSync('src/data/world.ts', ts);
console.log('rings', rings.length, 'paths', paths.length, 'bytes', ts.length);
