/**
 * The numbers the camera needs before the world has been fetched.
 *
 * Everything else — every coastline, border, lake, country name and city —
 * is in `public/veri/dunya.json`, requested the first time a reader pulls
 * back far enough to want it. Geometry is data, not code: bundling Natural
 * Earth into the map's JavaScript put most of a megabyte behind a 150 KB
 * budget for a layer most readers never open.
 *
 * These cannot wait for a fetch, because the zoom floor is derived from the
 * width of the planet and the camera has to be clamped on the first frame.
 *
 * GENERATED by scripts/build-world.mjs. Natural Earth is public domain.
 */

/** Where the network sits, for the marker drawn at world zoom. */
export const ISTANBUL = { x: 48.9, y: 41.9 };

/** The whole planet, in these units: 360 degrees of longitude. */
export const WORLD_W = 39130.4;

/** The left edge of one copy of it: the meridian at 180 degrees west. */
export const WORLD_X0 = -22673.9;

/** Units per degree of longitude, for turning a view width into a scale. */
export const UNITS_PER_DEG = 108.6957;

/** Where the rest of it lives. */
export const WORLD_URL = '/veri/dunya.json';

export interface WorldCountry {
  d: string;
  x: number;
  y: number;
  /** Draw the name once the view is narrower than this many degrees. */
  t: number;
  n: { en: string; tr: string; ar: string; ru: string };
}
export interface WorldCity {
  x: number;
  y: number;
  t: number;
  n: string;
  /** 1 if it is a national capital. */
  c: number;
}
export interface WorldData {
  countries: WorldCountry[];
  lakes: string[];
  cities: WorldCity[];
}
